language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
notifications:
  email:
    recipients:
      - rogger.valverde@uni.pe
    on_success: change
    on_failure: always
install:
  - yarn
after_success:
  - yarn semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"